name: poochpaw
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  google_sign_in: ^6.1.4
  shared_preferences: ^2.0.8
  email_validator: ^2.0.1
  string_validator: ^0.3.0
  image_picker: ^0.8.4+1
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.0.4
  flutter_svg: ^2.0.7
  flutter_local_notifications: ^15.1.0+1
  fl_chart: ^0.63.0
  universal_platform: ^1.0.0+1
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.11
  go_router: ^7.0.1
  dartx: ^1.1.0
  font_awesome_flutter: ^10.5.0
  cloud_firestore: ^4.8.3
  connectivity_plus: ^4.0.1
  flutter_facebook_auth: ^6.0.0
  http: ^1.1.0
  provider: ^6.0.5
  rounded_loading_button: ^2.1.0
  twitter_login: ^4.4.1
  timezone: ^0.9.2
  ionicons: ^0.2.2
  mime: ^1.0.4
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.4.0
  geolocator: ^11.0.0
  syncfusion_flutter_charts: ^25.2.7
  syncfusion_flutter_pdf: ^25.2.7
  permission_handler: ^11.3.1

  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git

  cached_network_image: ^3.2.2
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  file_picker: ^5.2.2

  # screen util
  flutter_screenutil: ^5.5.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.1
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.7.19
  flutter_rating_bar: ^4.0.1
  side_sheet: ^1.0.4
  bottom_sheet: ^4.0.4
  flutter_spinkit: ^5.2.1
  animate_do: ^3.3.4
  open_file: ^3.3.2
  crystal_navigation_bar: ^1.0.0
  iconly: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - lib/config/.env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Light.ttf
          weight: 300
        - asset: assets/fonts/Fredoka-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700

    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf
